# This file is generated by composer-plugin-nixify.
# Manual changes might be lost - proceed with caution!

{ lib, php, phpPackages, unzip, stdenv, runCommandLocal, writeText, fetchurl

# Default fetcher.
, fetcher ? (args: fetchurl { inherit (args) name urls sha256; })

}: src:

with lib;

let
  data = builtins.fromJSON ''
    {
    "cacheEntries": [
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "drupol_composer-plugin-nixify-2.0.7.0",
            "urls": [
                "https://api.github.com/repos/drupol/composer-plugin-nixify/zipball/56ece5e20dfa9402dd4058be35b893a08ed8aff1"
            ],
            "cacheFile": "drupol/composer-plugin-nixify/1e9ddfb441ea884c3aa529d65a4967447fd35c84.zip",
            "sha256": "8aff72b29081cd057dd4c87ca874ea0f67f8ae82cd879ee4824b311c9993d459"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "evenement_evenement-3.0.1.0",
            "urls": [
                "https://api.github.com/repos/igorw/evenement/zipball/531bfb9d15f8aa57454f5f0285b18bec903b8fb7"
            ],
            "cacheFile": "evenement/evenement/f6c182a8fe4c7a730c0e8f78a455a7d0ed7b79e7.zip",
            "sha256": "39a77a0722a40d361176a0010ac2958ed60a93d426435e84522c10f5320db10a"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "fig_http-message-util-1.1.5.0",
            "urls": [
                "https://api.github.com/repos/php-fig/http-message-util/zipball/9d94dc0154230ac39e5bf89398b324a86f63f765"
            ],
            "cacheFile": "fig/http-message-util/69466af17bb895e9c0ccc43c6828ba40608a4f07.zip",
            "sha256": "0edf5153b2dd9a2ded0b39aaf7eb6325deec1be53587e154c35421b82b6470b1"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "nikic_fast-route-1.3.0.0",
            "urls": [
                "https://api.github.com/repos/nikic/FastRoute/zipball/181d480e08d9476e61381e04a71b34dc0432e812"
            ],
            "cacheFile": "nikic/fast-route/9fc18cb64621a29fa485259432d1c2676733e347.zip",
            "sha256": "91dc73d089f6c9d77c189bd8df20c94144ff79c9c4a2429535cddc07ea8e586a"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "psr_http-message-1.0.1.0",
            "urls": [
                "https://api.github.com/repos/php-fig/http-message/zipball/f6561bf28d520154e4b0ec72be95418abe6d9363"
            ],
            "cacheFile": "psr/http-message/cc1d4e9ee13f2053b80c08976256789bf3be5256.zip",
            "sha256": "8538467ca2665fe15574f4d2506871823f71fd24b9a9284aae2ba90d8f69ada4"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "react_async-4.0.0.0",
            "urls": [
                "https://api.github.com/repos/reactphp/async/zipball/2aa8d89057e1059f59666e4204100636249b7be0"
            ],
            "cacheFile": "react/async/05f1122723af6861183d7e272a1f896ad8ecc9ac.zip",
            "sha256": "f0c0576b274ed07f0b1acd25693d9d669003b1faccececb9a9ec244e88ee9cda"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "react_cache-1.1.1.0",
            "urls": [
                "https://api.github.com/repos/reactphp/cache/zipball/4bf736a2cccec7298bdf745db77585966fc2ca7e"
            ],
            "cacheFile": "react/cache/652419660c38392fe1dc9525b03919f66271f6fb.zip",
            "sha256": "401a652aaf1d72649e60cd110b9c28c413aa84031ff2c99f6057f74d0b7b811e"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "react_dns-1.10.0.0",
            "urls": [
                "https://api.github.com/repos/reactphp/dns/zipball/a5427e7dfa47713e438016905605819d101f238c"
            ],
            "cacheFile": "react/dns/170ab6683464cf5a027f863b1fa04b05b5f606ad.zip",
            "sha256": "abc537181b11d6acdf766b663ca048d63b634a27fb2422ed456fd6d6278726b7"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "react_event-loop-1.3.0.0",
            "urls": [
                "https://api.github.com/repos/reactphp/event-loop/zipball/187fb56f46d424afb6ec4ad089269c72eec2e137"
            ],
            "cacheFile": "react/event-loop/633777bea66c5cb2ee33d1a69cd7aa0ca70f9ae3.zip",
            "sha256": "cc8798c9bede877c5e4488205e5b02e81f43887740075158fba7ff176d73ddda"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "react_http-1.8.0.0",
            "urls": [
                "https://api.github.com/repos/reactphp/http/zipball/aa7512ee17258c88466de30f9cb44ec5f9df3ff3"
            ],
            "cacheFile": "react/http/589c6d2c79a024ff4a9c475ba3dc16a954e65250.zip",
            "sha256": "d8c735a488fea24f527a5250326d908d650a1aed2483e3708f831d37a77efc23"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "react_promise-2.9.0.0",
            "urls": [
                "https://api.github.com/repos/reactphp/promise/zipball/234f8fd1023c9158e2314fa9d7d0e6a83db42910"
            ],
            "cacheFile": "react/promise/cfd94db0b393ae8a7d9db68f190f4e25093d5b62.zip",
            "sha256": "e4b7d5d279a0359bde65c46c82ad00e90e9f8148e0e7cd31c3e5784bbf34765c"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "react_promise-stream-1.5.0.0",
            "urls": [
                "https://api.github.com/repos/reactphp/promise-stream/zipball/e6d2805e09ad50c4896f65f5e8705fe4ee7731a3"
            ],
            "cacheFile": "react/promise-stream/18a86ac48ba16010adfbbbf3c3762315ba2f7f88.zip",
            "sha256": "49cddb118721d8c7a5a1379e7c469c58d5dd507fe9a9661b7e380821edc77d6e"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "react_promise-timer-1.9.0.0",
            "urls": [
                "https://api.github.com/repos/reactphp/promise-timer/zipball/aa7a73c74b8d8c0f622f5982ff7b0351bc29e495"
            ],
            "cacheFile": "react/promise-timer/a5e671eb8fe0131472b763769a5b7fe9002782b8.zip",
            "sha256": "edd582992426b16f41ebdc3b51f56f4dddbcff09c2661540b8f77970fc4af4a8"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "react_socket-1.12.0.0",
            "urls": [
                "https://api.github.com/repos/reactphp/socket/zipball/81e1b4d7f5450ebd8d2e9a95bb008bb15ca95a7b"
            ],
            "cacheFile": "react/socket/1b78009b15fd7f337ad866e41dbf24c0b79f65f8.zip",
            "sha256": "7b3b43f7116d0ed67c7648a7d9af0290fc9fda44be8110cba237a81a99ab4268"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "react_stream-1.2.0.0",
            "urls": [
                "https://api.github.com/repos/reactphp/stream/zipball/7a423506ee1903e89f1e08ec5f0ed430ff784ae9"
            ],
            "cacheFile": "react/stream/dba42d87e73249f3c93b323be9de3ad3c813b7f7.zip",
            "sha256": "ae828e015bf50fe009f074c3f3c83fc417ca6b836efc1d52020f1674443a96ed"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "ringcentral_psr7-1.3.0.0",
            "urls": [
                "https://api.github.com/repos/ringcentral/psr7/zipball/360faaec4b563958b673fb52bbe94e37f14bc686"
            ],
            "cacheFile": "ringcentral/psr7/02015452897e095772cc00c45f55b13acc25358c.zip",
            "sha256": "7c1800f3461229a46aaff6b4b7ef3aa685e2a94852505e00fbfe0de4ebd5a9c8"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "doctrine_instantiator-1.4.1.0",
            "urls": [
                "https://api.github.com/repos/doctrine/instantiator/zipball/10dcfce151b967d20fde1b34ae6640712c3891bc"
            ],
            "cacheFile": "doctrine/instantiator/b6977602bc07407dd2e3c71223021731d80df6d6.zip",
            "sha256": "e74aae2efad779dc6044b0b5d3ac4cf56eb41a511549ed35e6046cb4d6e0d7d4"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "myclabs_deep-copy-1.11.0.0",
            "urls": [
                "https://api.github.com/repos/myclabs/DeepCopy/zipball/14daed4296fae74d9e3201d2c4925d1acb7aa614"
            ],
            "cacheFile": "myclabs/deep-copy/8a47e905abc875fa8049c320097a46a9c305b50b.zip",
            "sha256": "3c357c9554caa4d6d71117ce8cfb7db23c1ac64eb28a1e659988cbcf201ba984"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "nikic_php-parser-4.15.1.0",
            "urls": [
                "https://api.github.com/repos/nikic/PHP-Parser/zipball/0ef6c55a3f47f89d7a374e6f835197a0b5fcf900"
            ],
            "cacheFile": "nikic/php-parser/1eb86a27836221d0f0d8af8423dabc73c22322d1.zip",
            "sha256": "6bc19dc410fd00ef6ca1be0594bb979e2e8fd5b143ea7a399b8fde92e2b8ba02"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "phar-io_manifest-2.0.3.0",
            "urls": [
                "https://api.github.com/repos/phar-io/manifest/zipball/97803eca37d319dfa7826cc2437fc020857acb53"
            ],
            "cacheFile": "phar-io/manifest/99001d1a4fa9041c56147e32147fb55de1cf9383.zip",
            "sha256": "3cb072c02dc066ff22531c8bb5bdf1a4e1dca6207c378218f75c4f4680d4ed80"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "phar-io_version-3.2.1.0",
            "urls": [
                "https://api.github.com/repos/phar-io/version/zipball/4f7fd7836c6f332bb2933569e566a0d6c4cbed74"
            ],
            "cacheFile": "phar-io/version/1495d1d88b1ae7e031b437037ce96298d897a969.zip",
            "sha256": "4f6f4fab8bfeac95934cec75be23743e38b6d864876f52dcdd5b54e003fcab55"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "phpunit_php-code-coverage-9.2.17.0",
            "urls": [
                "https://api.github.com/repos/sebastianbergmann/php-code-coverage/zipball/aa94dc41e8661fe90c7316849907cba3007b10d8"
            ],
            "cacheFile": "phpunit/php-code-coverage/68e2904371578d7cc1c1938fab1bf3a3928f4411.zip",
            "sha256": "41da9c4c409c06e9b093ca3bdfc4a835042a61f286af622eeffaf1eb01afe4da"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "phpunit_php-file-iterator-3.0.6.0",
            "urls": [
                "https://api.github.com/repos/sebastianbergmann/php-file-iterator/zipball/cf1c2e7c203ac650e352f4cc675a7021e7d1b3cf"
            ],
            "cacheFile": "phpunit/php-file-iterator/4fd4ef934d9b090aff1c14e5987f251c5d6b2d0c.zip",
            "sha256": "d9b2fe0929a3a844490dd9d32dbbd09a19713e3356e0199b26bc0c181c6a0790"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "phpunit_php-invoker-3.1.1.0",
            "urls": [
                "https://api.github.com/repos/sebastianbergmann/php-invoker/zipball/5a10147d0aaf65b58940a0b72f71c9ac0423cc67"
            ],
            "cacheFile": "phpunit/php-invoker/18d90380b8ff6f566265ca070b4bcfe4c4bbd34c.zip",
            "sha256": "d091fc2206ce86ff8664068b04952c8d8ff6dc12b7d864c1a8bf92c4adb416ef"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "phpunit_php-text-template-2.0.4.0",
            "urls": [
                "https://api.github.com/repos/sebastianbergmann/php-text-template/zipball/5da5f67fc95621df9ff4c4e5a84d6a8a2acf7c28"
            ],
            "cacheFile": "phpunit/php-text-template/b8d58f7d3789d6fd84cb6a82ebcb5776ab609787.zip",
            "sha256": "98a2b504e34e4b99e433f6d738b877d5847ea9b2800f7d8534f147eebf3fc839"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "phpunit_php-timer-5.0.3.0",
            "urls": [
                "https://api.github.com/repos/sebastianbergmann/php-timer/zipball/5a63ce20ed1b5bf577850e2c4e87f4aa902afbd2"
            ],
            "cacheFile": "phpunit/php-timer/b71ded866a460bbdb922b5eb818f4ed163f38f0c.zip",
            "sha256": "cacc8ec54d593bfaa1627bc67e110b0ef9d2f1d2ae98007d8b2bcc4fbc3f2f3c"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "phpunit_phpunit-9.5.25.0",
            "urls": [
                "https://api.github.com/repos/sebastianbergmann/phpunit/zipball/3e6f90ca7e3d02025b1d147bd8d4a89fd4ca8a1d"
            ],
            "cacheFile": "phpunit/phpunit/f5978d7774789a39edc093e9fa4d78eb1bff1227.zip",
            "sha256": "8384362f655a22f25366992d9b2e50ac83793945fa8fe1a9bdbe8cbcf0df0b81"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "psr_container-2.0.2.0",
            "urls": [
                "https://api.github.com/repos/php-fig/container/zipball/c71ecc56dfe541dbd90c5360474fbc405f8d5963"
            ],
            "cacheFile": "psr/container/a0a43e15cb16e3ab95a991e1bffc813474b15cdf.zip",
            "sha256": "3111f5b69d3a0f690f5f92d7aeacfb247f5ebd3c175088cce4b098e5d1b06ad7"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "sebastian_cli-parser-1.0.1.0",
            "urls": [
                "https://api.github.com/repos/sebastianbergmann/cli-parser/zipball/442e7c7e687e42adc03470c7b668bc4b2402c0b2"
            ],
            "cacheFile": "sebastian/cli-parser/f4b297cc8d9ba3ba47f6d1c84b9d69bac882a7b1.zip",
            "sha256": "6740017ab612481526b458876d8a9aba23326099ca0e0cb7263dcd1470fb981c"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "sebastian_code-unit-1.0.8.0",
            "urls": [
                "https://api.github.com/repos/sebastianbergmann/code-unit/zipball/1fc9f64c0927627ef78ba436c9b17d967e68e120"
            ],
            "cacheFile": "sebastian/code-unit/2175508c3a7c4f57c236668e95692cb4f230ef7e.zip",
            "sha256": "f51e89b8ecce2a310a2cef0d7e8256378540fe1da91daa7a25a5e50c0ae87413"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "sebastian_code-unit-reverse-lookup-2.0.3.0",
            "urls": [
                "https://api.github.com/repos/sebastianbergmann/code-unit-reverse-lookup/zipball/ac91f01ccec49fb77bdc6fd1e548bc70f7faa3e5"
            ],
            "cacheFile": "sebastian/code-unit-reverse-lookup/68fb878dfd88a53caa52899dcad6f00ede9925b2.zip",
            "sha256": "4a6a9beb03ba89c65df74e0200eef997aed640f362a94a224e61aa3ffe5f32c0"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "sebastian_comparator-4.0.8.0",
            "urls": [
                "https://api.github.com/repos/sebastianbergmann/comparator/zipball/fa0f136dd2334583309d32b62544682ee972b51a"
            ],
            "cacheFile": "sebastian/comparator/6a8576886b5e1cfd55783584d8a948ab21adc37c.zip",
            "sha256": "7ca0bc15be7811ff9964e059889466bab579a93f7ed34cd02e58f0aef85c1155"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "sebastian_complexity-2.0.2.0",
            "urls": [
                "https://api.github.com/repos/sebastianbergmann/complexity/zipball/739b35e53379900cc9ac327b2147867b8b6efd88"
            ],
            "cacheFile": "sebastian/complexity/76ac0bc95bb26576a1588ac4917fe13f3107573f.zip",
            "sha256": "ce23bcd6c0fe24007e0ad6bf3cc17fa7beedf11dfdc6e46c84eb6b882cfa9ef8"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "sebastian_diff-4.0.4.0",
            "urls": [
                "https://api.github.com/repos/sebastianbergmann/diff/zipball/3461e3fccc7cfdfc2720be910d3bd73c69be590d"
            ],
            "cacheFile": "sebastian/diff/527dd851ed7cdbd6b86e440441567b594e489fde.zip",
            "sha256": "b209732f1736f8eb065781ac87b69bc0d8a752f19df0813ed820dbc60cb5c724"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "sebastian_environment-5.1.4.0",
            "urls": [
                "https://api.github.com/repos/sebastianbergmann/environment/zipball/1b5dff7bb151a4db11d49d90e5408e4e938270f7"
            ],
            "cacheFile": "sebastian/environment/0b7f292f62f46ed49ae0d70b39bfa393b4211611.zip",
            "sha256": "2119946edb20c6bde2b716a4c85a0ef2e6ec96abc365c50ffc0044986e551762"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "sebastian_exporter-4.0.5.0",
            "urls": [
                "https://api.github.com/repos/sebastianbergmann/exporter/zipball/ac230ed27f0f98f597c8a2b6eb7ac563af5e5b9d"
            ],
            "cacheFile": "sebastian/exporter/d097047a341fb0e411c70e540a62a9ca3af9479c.zip",
            "sha256": "d290d6d4c1ed86927a833cc9cceb9fefb4b55d6cda7774e38b43f28c3692dea8"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "sebastian_global-state-5.0.5.0",
            "urls": [
                "https://api.github.com/repos/sebastianbergmann/global-state/zipball/0ca8db5a5fc9c8646244e629625ac486fa286bf2"
            ],
            "cacheFile": "sebastian/global-state/1cf3bc48e84c37ec54b03a90443ac94230cef95b.zip",
            "sha256": "e14d22f89153d22e02b21b305a34258e43992ef7ab3a2ac2517fc7b38a7259b3"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "sebastian_lines-of-code-1.0.3.0",
            "urls": [
                "https://api.github.com/repos/sebastianbergmann/lines-of-code/zipball/c1c2e997aa3146983ed888ad08b15470a2e22ecc"
            ],
            "cacheFile": "sebastian/lines-of-code/c83c674fbb96cf1b9525472250a2ec5c8e7784d6.zip",
            "sha256": "60ae97d500e9d96e826afb01b5789c511fdb7fe6304a7c325fcf84ca8a4e5e39"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "sebastian_object-enumerator-4.0.4.0",
            "urls": [
                "https://api.github.com/repos/sebastianbergmann/object-enumerator/zipball/5c9eeac41b290a3712d88851518825ad78f45c71"
            ],
            "cacheFile": "sebastian/object-enumerator/da625947c9c4e28182677035866359692138e8aa.zip",
            "sha256": "c132dcacda3e4e0967aeabf068fa83f3f492a351c34bcd8f5101227ec01f0585"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "sebastian_object-reflector-2.0.4.0",
            "urls": [
                "https://api.github.com/repos/sebastianbergmann/object-reflector/zipball/b4f479ebdbf63ac605d183ece17d8d7fe49c15c7"
            ],
            "cacheFile": "sebastian/object-reflector/89595d8936651649889c35a91221207e12331fda.zip",
            "sha256": "4f673297cc7e85c41c8658c202e01ead4adae48d6c870ec070941bcfb50bb53c"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "sebastian_recursion-context-4.0.4.0",
            "urls": [
                "https://api.github.com/repos/sebastianbergmann/recursion-context/zipball/cd9d8cf3c5804de4341c283ed787f099f5506172"
            ],
            "cacheFile": "sebastian/recursion-context/6458bc6eb2e2dab0f0e7550c596001dd26243950.zip",
            "sha256": "fe429b1e155104d66e0a930e44853d0a3daf790965f0a57712c3609e678813cc"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "sebastian_resource-operations-3.0.3.0",
            "urls": [
                "https://api.github.com/repos/sebastianbergmann/resource-operations/zipball/0f4443cb3a1d92ce809899753bc0d5d5a8dd19a8"
            ],
            "cacheFile": "sebastian/resource-operations/c70bff160e611fd40d5d68d1f06d580b9496fb3a.zip",
            "sha256": "d92f4b5b50d5e264d3b00ab31a3b80c0718f2689a1f3f23d101ce67a6e46ba5c"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "sebastian_type-3.2.0.0",
            "urls": [
                "https://api.github.com/repos/sebastianbergmann/type/zipball/fb3fe09c5f0bae6bc27ef3ce933a1e0ed9464b6e"
            ],
            "cacheFile": "sebastian/type/e4452efb1e3255d8306d160c941ba887a0c693b5.zip",
            "sha256": "67748a67088f019de35d5a1213bb1f4e6954b6b20d62a234fef1cd615f4a95d2"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "sebastian_version-3.0.2.0",
            "urls": [
                "https://api.github.com/repos/sebastianbergmann/version/zipball/c6c1022351a901512170118436c764e473f6de8c"
            ],
            "cacheFile": "sebastian/version/85e202da271e8389420827021d6c4f00bdd90951.zip",
            "sha256": "e1c5424e05207360f511745290144dcad1df69f1789fd97eb0d1819a145f47af"
        },
        {
            "package": {
                "id": -1
            },
            "type": "cache",
            "name": "theseer_tokenizer-1.2.1.0",
            "urls": [
                "https://api.github.com/repos/theseer/tokenizer/zipball/34a41e998c2183e22995f158c581e7b5e755ab9e"
            ],
            "cacheFile": "theseer/tokenizer/9c419ba4ed9d43ff57a21270f44363ad0bed22f7.zip",
            "sha256": "18d8c32441b19070ed7643321f5d3d5ee07217b991bee605cf64c979025044fd"
        }
    ],
    "projectName": "clue_framework-x"
}
  '';
  composerPath = data.composerPath or phpPackages.composer.src;
  cacheEntries = data.cacheEntries or [];
  localEntries = data.localEntries or [];

  # Shell snippet to collect all project dependencies.
  collectCacheScript = writeText "collect-cache.sh" (
    concatMapStrings (args: ''
      (
        cacheFile=${escapeShellArg args.cacheFile}
        cacheFilePath="$COMPOSER_CACHE_DIR/files/$cacheFile"
        mkdir -p "$(dirname "$cacheFilePath")"
        cp ${escapeShellArg (fetcher args)} "$cacheFilePath"
      )
    '') cacheEntries
  );

  replaceLocalPaths = writeText "replace-local-paths.sh" (
    concatMapStrings (args: ''
      sed -i -e "s|\"${args.string}\"|\"${args.path}\"|" composer.lock
    '') localEntries
  );

in stdenv.mkDerivation {
  name = data.projectName;
  inherit src;

  # Make sure the build uses the right PHP version everywhere.
  # Also include unzip for Composer.
  buildInputs = [ php unzip ];

  # Defines the shell alias to run Composer.
  postHook = ''
    composer () {
      php "$NIX_COMPOSER_PATH" "$@"
    }
  '';

  configurePhase = ''
    runHook preConfigure

    # Set the cache directory for Composer.
    export COMPOSER_CACHE_DIR="$NIX_BUILD_TOP/.composer/cache"

    # Build the cache directory contents.
    source ${collectCacheScript}

    # Replace local package paths with their Nix store equivalent.
    source ${replaceLocalPaths}

    # Store the absolute path to Composer for the 'composer' alias.
    export NIX_COMPOSER_PATH="$(readlink -f ${escapeShellArg composerPath})"

    # Run normal Composer install to complete dependency installation.
    composer install -n -o

    runHook postConfigure
  '';

  buildPhase = ''
    runHook preBuild
    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p $out/libexec $out/bin

    # Move the entire project to the output directory.
    mv $PWD "$out/libexec/$sourceRoot"
    cd "$out/libexec/$sourceRoot"

    # Update the path to Composer.
    export NIX_COMPOSER_PATH="$(readlink -f ${escapeShellArg composerPath})"

    # Invoke a plugin internal command to setup binaries.
    # composer nixify-install-bin "$out/bin"

    runHook postInstall
  '';

  passthru = {
    inherit php;
  };
}
